# Generated by Django 6.0.3 on 2026-03-26 16:10

import vehicles.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='price_per_day',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[vehicles.models.validate_positive_price]),
        ),
    ]
